import {
  pgTable,
  uuid,
  text,
  integer,
  timestamp,
  jsonb,
  boolean,
  pgEnum,
  numeric,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const matchStatus = pgEnum("match_status", [
  "scheduled",
  "live",
  "final",
]);

export const matchBetStatus = pgEnum("match_bet_status", [
  "open",
  "settled",
  "void",
]);

export const outcome = pgEnum("outcome", ["pending", "won", "lost"]);

export const wagerStatus = pgEnum("wager_status", [
  "open",
  "won",
  "lost",
  "void",
]);

export const customBetStatus = pgEnum("custom_bet_status", [
  "open",
  "locked",
  "settled",
  "void",
]);

export const settlementKind = pgEnum("settlement_kind", [
  "match",
  "custom_bet",
  "void_custom_bet",
]);

export const rooms = pgTable("rooms", {
  id: uuid("id").primaryKey().defaultRandom(),
  code: text("code").notNull().unique(),
  name: text("name").notNull(),
  startingChips: integer("starting_chips").notNull().default(1000),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const users = pgTable(
  "users",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    roomId: uuid("room_id")
      .notNull()
      .references(() => rooms.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    chips: integer("chips").notNull(),
    isCreator: boolean("is_creator").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("users_room_idx").on(t.roomId),
    uniqueIndex("users_room_name_idx").on(t.roomId, t.name),
  ]
);

// Score odds cache shape:
//   { "0-0": 9.12, "1-0": 7.40, "1-1": 6.20, ... }  — decimal odds for that exact score
export type ScoreOddsCache = Record<string, number>;

export const matches = pgTable(
  "matches",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    groupLabel: text("group_label").notNull(), // 'A'..'L' or 'R16'/'QF'/'SF'/'F'/'3RD'
    homeTeam: text("home_team").notNull(),
    awayTeam: text("away_team").notNull(),
    kickoff: timestamp("kickoff", { withTimezone: true }).notNull(),
    status: matchStatus("status").notNull().default("scheduled"),
    homeScore: integer("home_score"),
    awayScore: integer("away_score"),
    // Direction (1X2) decimal odds — generated by Claude.
    oddsHome: numeric("odds_home", { precision: 5, scale: 2 }),
    oddsDraw: numeric("odds_draw", { precision: 5, scale: 2 }),
    oddsAway: numeric("odds_away", { precision: 5, scale: 2 }),
    // Exact-score decimal odds for every score 0-0 through 9-9.
    // null if not yet generated.
    scoreOdds: jsonb("score_odds").$type<ScoreOddsCache>(),
  },
  (t) => [
    index("matches_kickoff_idx").on(t.kickoff),
    index("matches_status_idx").on(t.status),
  ]
);

// One row per (user, match) — a single predicted score that creates two
// implicit bets: one on direction (HOME/DRAW/AWAY) and one on the exact
// score. The user's total stake is split 50/50 between them.
export const matchBets = pgTable(
  "match_bets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    roomId: uuid("room_id")
      .notNull()
      .references(() => rooms.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    matchId: uuid("match_id")
      .notNull()
      .references(() => matches.id, { onDelete: "cascade" }),
    predictedHomeScore: integer("predicted_home_score").notNull(),
    predictedAwayScore: integer("predicted_away_score").notNull(),
    totalStake: integer("total_stake").notNull(),
    directionStake: integer("direction_stake").notNull(),
    scoreStake: integer("score_stake").notNull(),
    directionOddsLocked: numeric("direction_odds_locked", {
      precision: 5,
      scale: 2,
    }).notNull(),
    scoreOddsLocked: numeric("score_odds_locked", {
      precision: 6,
      scale: 2,
    }).notNull(),
    status: matchBetStatus("status").notNull().default("open"),
    directionOutcome: outcome("direction_outcome").notNull().default("pending"),
    scoreOutcome: outcome("score_outcome").notNull().default("pending"),
    payout: integer("payout"), // total chips credited at settle
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("match_bets_one_per_user_per_match").on(
      t.roomId,
      t.userId,
      t.matchId
    ),
    index("match_bets_room_idx").on(t.roomId),
    index("match_bets_match_idx").on(t.matchId),
  ]
);

// Options shape stored in jsonb:
//   [{ label: "Yes", probability: 0.42, odds: 2.38 }, ...]
export type CustomBetOption = {
  label: string;
  probability: number;
  odds: number;
};

export const customBets = pgTable(
  "custom_bets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    roomId: uuid("room_id")
      .notNull()
      .references(() => rooms.id, { onDelete: "cascade" }),
    matchId: uuid("match_id").references(() => matches.id, {
      onDelete: "set null",
    }),
    proposerId: uuid("proposer_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    description: text("description").notNull().default(""),
    options: jsonb("options").$type<CustomBetOption[]>().notNull(),
    aiReasoning: text("ai_reasoning").notNull().default(""),
    status: customBetStatus("status").notNull().default("open"),
    winningOptionIdx: integer("winning_option_idx"),
    locksAt: timestamp("locks_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("custom_bets_room_idx").on(t.roomId),
    index("custom_bets_match_idx").on(t.matchId),
    index("custom_bets_status_idx").on(t.status),
  ]
);

export const customWagers = pgTable(
  "custom_wagers",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    customBetId: uuid("custom_bet_id")
      .notNull()
      .references(() => customBets.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    optionIdx: integer("option_idx").notNull(),
    stake: integer("stake").notNull(),
    oddsLocked: numeric("odds_locked", { precision: 5, scale: 2 }).notNull(),
    status: wagerStatus("status").notNull().default("open"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("custom_wagers_bet_idx").on(t.customBetId),
    index("custom_wagers_user_idx").on(t.userId),
  ]
);

// Audit log so settlements can be reviewed by any room member.
export const settlements = pgTable(
  "settlements",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    roomId: uuid("room_id")
      .notNull()
      .references(() => rooms.id, { onDelete: "cascade" }),
    actorId: uuid("actor_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    kind: settlementKind("kind").notNull(),
    targetId: uuid("target_id").notNull(), // match.id or custom_bet.id
    payload: jsonb("payload").notNull().default(sql`'{}'::jsonb`),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [index("settlements_room_idx").on(t.roomId)]
);

export type Room = typeof rooms.$inferSelect;
export type User = typeof users.$inferSelect;
export type Match = typeof matches.$inferSelect;
export type MatchBet = typeof matchBets.$inferSelect;
export type CustomBet = typeof customBets.$inferSelect;
export type CustomWager = typeof customWagers.$inferSelect;
export type Settlement = typeof settlements.$inferSelect;

export function scoreKey(home: number, away: number): string {
  return `${home}-${away}`;
}

export const SCORE_RANGE = 10; // 0..9 inclusive on each side (100 cells)
